// Generates the consumer-facing ambient global declarations from the device
// definitions — the single source of truth. Run after the dev bundle is built
// (it reads the compiled UMD bundle, which is safe to require in Node: the p5
// addon auto-registration is guarded by `typeof p5 !== 'undefined'`).

const fs = require('fs');
const path = require('path');

const bundlePath = path.resolve(__dirname, '../dist/p5.nanokontrol2.js');
if (!fs.existsSync(bundlePath)) {
  console.error(`gen-types: ${bundlePath} not found — run the webpack build first.`);
  process.exit(1);
}

const lib = require(bundlePath);
const names = lib.NANOKONTROL2_DEF.controls.map((c) => c.name);

// Group names by their leading token for readable, commented output.
const lines = names.map((n) => `  const ${n}: string;`).join('\n');

const content = `// AUTO-GENERATED by scripts/gen-types.js — do not edit by hand.
//
// Consumer-facing ambient declarations. In p5 "global mode" (the usual sketch
// style) the addon exposes its class and input constants as window globals.
// This file declares them so TypeScript sketch authors get autocomplete and
// type-checking. Reference it from a sketch with:
//   /// <reference path="./dist/types/p5.nanokontrol2.d.ts" />
//
// The control-name constants below are derived from the device definitions in
// src/devices/. The inputChanged/buttonPressed/buttonReleased callbacks are
// defined by the sketch author, so they are intentionally not declared here.

import type { MidiController } from './MidiController';
import type { MidiControllerOptions } from './types';

export {};

declare global {
  /** Device-specific controller for the KORG nanoKONTROL2. */
  const NanoKontrol2: new (options?: MidiControllerOptions) => MidiController;

  /** Generic engine for defining custom controllers. */
  const MidiController: typeof import('./MidiController').MidiController;

  /** Input mode constant. */
  const RAW: string;

  // Control-name constants (derived from src/devices/).
${lines}
}
`;

const outPath = path.resolve(__dirname, '../dist/types/p5.nanokontrol2.d.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
console.log(`gen-types: wrote ${path.relative(process.cwd(), outPath)} (${names.length} control constants)`);
